version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"   # pour Flask
      - "8501:8501"   # pour Streamlit
    environment:
      - APP_MODE=flask  # ou "streamlit" selon le cas
    volumes:
      - .:/app
